# Generated by Django 2.0.4 on 2018-04-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesinfo',
            name='data_source',
            field=models.IntegerField(choices=[(0, '程序产生'), (1, '人工录入'), (2, '其他')], default=0),
        ),
    ]
