# Generated by Django 2.0.4 on 2018-05-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_server', '0002_tablesinfo_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfilelog',
            name='project_conf',
            field=models.FileField(upload_to='project_conf/'),
        ),
    ]
